---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cron-hpa.fullname" . }}
  labels:
    {{- include "cron-hpa.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cron-hpa.ubie-oss.github.com
  resources:
  - cronhorizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cron-hpa.ubie-oss.github.com
  resources:
  - cronhorizontalpodautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - cron-hpa.ubie-oss.github.com
  resources:
  - cronhorizontalpodautoscalers/status
  verbs:
  - get
  - patch
  - update
