name: Test
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: set up
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go
    - name: check out
      uses: actions/checkout@v2
    - name: before cache
      run: |
        mkdir -p ~/go/pkg/mod
    - name: Cache
      uses: actions/cache@v2.1.0
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: make build
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.42.1
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: make test
    - uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: cover.out
