name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out
      uses: actions/checkout@v3
    - name: set up
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        check-latest: true
        cache-dependency-path: go.sum
    - name: build
      run: make build
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: check out
      uses: actions/checkout@v3
    - name: set up
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        check-latest: true
        cache-dependency-path: go.sum
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.42.1
  test:
    runs-on: ubuntu-latest
    steps:
    - name: check out
      uses: actions/checkout@v3
    - name: set up
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        check-latest: true
        cache-dependency-path: go.sum
    - name: test
      run: make test
    - uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: cover.out
